![alt text](https://whatsthebigdata.files.wordpress.com/2017/06/data-science-machine-learning-software-2015-2017.jpg)

##**NumPy**


NumPy(Numerical Python) is a linear algebra library in Python. Why learning NumPy is important:

1.   NumPy is very useful for performing mathematical and logical operations on Arrays. 
2.   NumPy provides an abundance of useful features for operations on n-arrays and matrices in Python.

NumPy is a very important library on which almost every data science or machine learning Python packages such as SciPy(Scientific Python), Mat-plotlib(plotting library), Scikit-learn, etc depends on to a reasonable extent.

Documentation - https://numpy.org/doc/

###**Import Numpy and Pandas Libraries**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print ("NumPy version - " + np.version.version)

NumPy version - 1.18.2


###**Creating Arrays**

####Creating 1 D *Numpy Arrays*

In [ ]:
#create 1D numpy array from a list
array_1d = np.array([1, 2, 3, 4, 5])

print (array_1d)

[1 2 3 4 5]


In [ ]:
#create 1D numpy array from a list variable
list_1 = [11, 22, 33, 44, 55]
array_l1 = np.array(list_1)

print(array_l1)

[11 22 33 44 55]


In [ ]:
#print the type of an numpy array we created
print ("Array type = " + str(type(array_1d)))

#print the data type 
print ("Data type = " + str(array_1d.dtype))

Array type = <class 'numpy.ndarray'>
Data type = int64


In [ ]:
#check the shape of the ndarray we created, it should have only 1 dimension
print(array_1d.shape)

(5,)


In [ ]:
type(array_1d)

numpy.ndarray

In [ ]:
#Demonstrating the Range function.
plain_range = range(4,12)
list(plain_range)

[4, 5, 6, 7, 8, 9, 10, 11]

Notice how the second number is exclusive. 

In [ ]:
interval_range = range(1, 15, 2)

In [ ]:
list(interval_range)

[1, 3, 5, 7, 9, 11, 13]

### Your Turn!

1. Create your own Python List using the range function.
2. Convert the list into a NumPy array
3. Check the data type to make sure it is a NumPy array
4. Convert that array back into a list



In [ ]:
list(range(15, 1, -2))

[15, 13, 11, 9, 7, 5, 3]

### Python Matrices (2D) to NumPy Array

In [ ]:
# mymatrix = [[4,2,9],[32,43,68],[73,8,9]]
# mymatrix
mymatrix = [list(range(1,10,1)),list(range(2,12,1))]
mymatrix

[[1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]

In [ ]:
#Create a matrix (2D array)
numpy_array = np.array(mymatrix)

In [ ]:
numpy_array

array([[ 4,  2,  9],
       [32, 43, 68],
       [73,  8,  9]])

In [ ]:
type(numpy_array)

list

### Convert a NumPy Array into a Pandas DataFrame

In [ ]:
df_from_array = pd.DataFrame(numpy_array)
df_from_array

0   1   2
0   4   2   9
1  32  43  68
2  73   8   9

### Your Turn!

1. Create your own Python matrix
2. Convert the matrix into a NumPy array
3. Check the data type to make sure it is a NumPy array
4. Convert the NumPy array to a Pandas DataFrame

### Python Data Types

In [ ]:
type(4)

int

In [ ]:
type(4.0)

float

In [ ]:
type('4353')

str

In [ ]:
type('Hello')

str

DateTime function

In [ ]:
import datetime
datetime_example = datetime.datetime.now()
print(datetime_example)

2020-03-27 19:35:49.909019


In [ ]:
type(datetime_example)

datetime.datetime

In [ ]:
another_list = [23, [34, 21], 'Google']
another_list

[23, [34, 21], 'Google']

###**Indexing, Slice indexing**

We can use slice indexing to pull out sub-regions of ndarrays

More documentation can be found at https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

In [ ]:
#create 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7])
print (array_1d)

[1 2 3 4 5 6 7]


In [ ]:
#because we have 1D array, we need only one index to access element at any position
#call the value at index 2
print ('element at index 2: ', array_1d[2])

#ndarrays are mutable, here we change an element at index 2 
array_1d[2] = 10
print ('element at index 2 after change: ', array_1d[2])

element at index 2:  3
element at index 2 after change:  10


In [ ]:
print (array_1d)

[ 1  2 10  4  5  6  7]


In [ ]:
#get the values in the range
print ('elements in the range: ', array_1d[1:3]) #a:b - including a, until (and excluding) b

#we can change values in the range as well
array_1d[1:3] = 20
print ('elements in the range after change: ', array_1d[1:3])

elements in the range:  [ 2 10]
elements in the range after change:  [20 20]


In [ ]:
#for 2D arrays we will need two indexing first one for the row and second one for the column
#create 2D array
array_2d = np.array([[11, 12, 13, 14, 15, 16, 17], [21, 22, 23, 24, 25, 26, 27], [31, 32, 33, 34, 35, 36, 37]])
print ('original array: \n', array_2d, '\n')

#slicing: generates an array of the same rank
array_copy = array_2d.copy()
slice_row = array_copy[1:2, :] #a:b - including a, until (and excluding) b
print ('sliced array on [1:2, :]: \n', slice_row)

original array: 
 [[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]] 

sliced array on [1:2, :]: 
 [[21 22 23 24 25 26 27]]


In [ ]:
#if we change the sliced array it will changed the original array too
slice_row[:, :] = 10

print ('sliced array: \n', slice_row, '\n')
print ('original array: \n', array_2d)


sliced array: 
 [[10 10 10 10 10 10 10]] 

original array: 
 [[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]]


In [ ]:
#we can do the slicing for columns as well
slice_col = array_2d[:, 1:5]
print (slice_col)

[[12 13 14 15]
 [22 23 24 25]
 [32 33 34 35]]


In [ ]:
#we can use filters to select just those elements which meet certain criteria 
#select the elements that are greater than 10
slice_col[slice_col>10]

array([12, 13, 14, 15, 22, 23, 24, 25, 32, 33, 34, 35])

In [ ]:
#use similar logical filter to change elements in the array
#add 1 to all the odd values
slice_col[slice_col % 2 == 1] += 1
slice_col

array([[12, 14, 14, 16],
       [22, 24, 24, 26],
       [32, 34, 34, 36]])

###**Arithmetic array operations**

More documentation at https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

In [ ]:
#addition can be done with the plus sign or 'add' numpy function
arr_x = np.array([[10, 20, 30], [40, 50, 60]])
arr_y = np.array([[11, 21, 31], [41, 51, 61]])

print("Array X")
print(arr_x, '\n')

print("Array Y")
print(arr_y, '\n')

print("Direct Addition")
print (arr_x + arr_y, '\n')

print("Numpy Addition")
print (np.add(arr_x, arr_y))

Array X
[[10 20 30]
 [40 50 60]] 

Array Y
[[11 21 31]
 [41 51 61]] 

Direct Addition
[[ 21  41  61]
 [ 81 101 121]] 

Numpy Addition
[[ 21  41  61]
 [ 81 101 121]]


In [ ]:
#the same is with the subtraction 
print("Direct Subtraction")
print (arr_y - arr_x, '\n')

print("Numpy Subtraction")
print (np.subtract(arr_y, arr_x))

Direct Subtraction
[[1 1 1]
 [1 1 1]] 

Numpy Subtraction
[[1 1 1]
 [1 1 1]]


In [ ]:
#multiplication
print("Direct Multiplication")
print (arr_x * arr_y, '\n')

print("Numpy Multiplication")
print (np.multiply(arr_x, arr_y))

Direct Multiplication
[[ 110  420  930]
 [1640 2550 3660]] 

Numpy Multiplication
[[ 110  420  930]
 [1640 2550 3660]]


In [ ]:
#division
print("Direct Division")
print (arr_y / arr_x, '\n')

print("Numpy Division")
print (np.divide(arr_y, arr_x))

Direct Division
[[1.1        1.05       1.03333333]
 [1.025      1.02       1.01666667]] 

Numpy Division
[[1.1        1.05       1.03333333]
 [1.025      1.02       1.01666667]]


In [ ]:
#square root

print (np.sqrt(arr_x))

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [ ]:
#exponent (e**x)

print (np.exp(arr_x))

[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]


In [ ]:
#power

print (np.power(arr_x, 3))

[[  1000   8000  27000]
 [ 64000 125000 216000]]


###**Statistical methods**

More documentation at https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html


In [ ]:
#create random 4x6 matrix
arr = np.random.randn(4,6)
print (arr)

[[ 1.54301581  0.22584563 -0.56942715 -0.14282126 -0.63833379  0.63642757]
 [ 1.01708328 -0.00330621 -0.44513793 -1.26833574  0.68080274  1.56888582]
 [-0.90435376  1.4901251   0.02696174 -0.66356751  0.76130201 -0.67236148]
 [-1.24613979  1.53691069  0.55528904  0.44450692  0.25006921  0.77945527]]


In [ ]:
#compute the mean for all elements
print (arr.mean())

0.20678734245045097


In [ ]:
#compute the mean by row
print (arr.mean(axis = 1))

[0.17578447 0.25833199 0.00635102 0.38668189]


In [ ]:
#compute mean by column
print (arr.mean(axis = 0))

[ 0.10240138  0.8123938  -0.10807858 -0.4075544   0.26346004  0.5781018 ]


In [ ]:
#compute the median for all elements, by row or column can be done the same way as for mean
print (np.median(arr))

0.23795741772640938


*what does axis mean?* https://stackoverflow.com/questions/22149584/what-does-axis-in-pandas-mean


In [ ]:
#sum of all the elements, by row or column can be done the same way as for mean
print (np.sum(arr))

4.962896218810823


In [ ]:
arr

array([[ 1.54301581,  0.22584563, -0.56942715, -0.14282126, -0.63833379,
         0.63642757],
       [ 1.01708328, -0.00330621, -0.44513793, -1.26833574,  0.68080274,
         1.56888582],
       [-0.90435376,  1.4901251 ,  0.02696174, -0.66356751,  0.76130201,
        -0.67236148],
       [-1.24613979,  1.53691069,  0.55528904,  0.44450692,  0.25006921,
         0.77945527]])

###**Read, or Write to disc**

In [ ]:
np.savetxt('array.txt', X = arr, delimiter = ',')

In [ ]:
np.loadtxt('array.txt', delimiter = ',')

array([[ 1.54301581,  0.22584563, -0.56942715, -0.14282126, -0.63833379,
         0.63642757],
       [ 1.01708328, -0.00330621, -0.44513793, -1.26833574,  0.68080274,
         1.56888582],
       [-0.90435376,  1.4901251 ,  0.02696174, -0.66356751,  0.76130201,
        -0.67236148],
       [-1.24613979,  1.53691069,  0.55528904,  0.44450692,  0.25006921,
         0.77945527]])

##**Pandas**
Pandas is an numerical open source python library that is built on top of NumPy. Why learning Pandas is important:

Pandas allows you do fast analysis as well as data cleaning and preparation
Pandas can work well with data from a wide variety of sources such as; Excel sheet, csv file, sql file or even a webpage

Documentation - https://pandas.pydata.org/pandas-docs/version/0.25.3/

###**Pandas Series**

Pandas series are one-dimensional labeled array that are capable of holding of data of any type

In [ ]:
#creating panda series from list
ls = ['a', 'b', 'c', 'd', 'e']
ser_1 = pd.Series(ls)

print (ser_1)

0    a
1    b
2    c
3    d
4    e
dtype: object


In [ ]:
#creating panda series from array
arr = np.array([10, 20, 30, 40, 50])
ser_2 = pd.Series(arr)

print (ser_2)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
#create series with specific indexing
ser_3 = pd.Series(arr, index = ['sarah', 'bob', 'alex', 'den', 'nancy'])

print (ser_3)

sarah    10
bob      20
alex     30
den      40
nancy    50
dtype: int64


In [ ]:
#accessing an element using the index 
print (ser_3[3], '\n\n')
print (ser_3[[0, 2, 4]], '\n\n')
print (ser_3[:3])

40 


sarah    10
alex     30
nancy    50
dtype: int64 


sarah    10
bob      20
alex     30
dtype: int64


In [ ]:
#accessing element using an index label
print (ser_3['den'], '\n\n')
print (ser_3[['den', 'alex', 'sarah']])

40 


den      40
alex     30
sarah    10
dtype: int64


### Create a Pandas DataFrame

Pandas DataFrame is a two-dimensional labeled data structure.

In [ ]:
#Creating from a list of lists
pet_info = [['Blain', 10, 'Dog'], ['Lucy', 4 , 'Cat'], ['Cinco', 8, 'Rabbit']]
pet_info

[['Blain', 10, 'Dog'], ['Lucy', 4, 'Cat'], ['Cinco', 8, 'Rabbit']]

In [ ]:
pet_df = pd.DataFrame(pet_info, columns = ['Name', 'Age', 'Type'],
                      index = ['A', 'B', 'C'])
                     
pet_df

Name  Age    Type
A  Blain   10     Dog
B   Lucy    4     Cat
C  Cinco    8  Rabbit

In [ ]:
pet_df['Name']

A    Blain
B     Lucy
C    Cinco
Name: Name, dtype: object

### Your Turn!

Print out the 'Type' Column

In [ ]:
type(pet_df)

pandas.core.frame.DataFrame

In [ ]:
pet_df.dtypes

Name    object
Age      int64
Type    object
dtype: object

### Your Turn!



In [ ]:
#Create a list of lists that contain [[Month, Month #(Dec=12, etc.), Season]]
#Create a Pandas DataFrame with the columns = ['Month', 'Int', 'Season']

### iloc vs. loc

iloc - position-based indexing (index always starts with 0)

loc - label-based indexing

If you don't specify indexes, then iloc and loc will be the same

In [ ]:
pet_df.iloc[0]

Name    Blain
Age        10
Type      Dog
Name: A, dtype: object

In [ ]:
pet_df.loc['B']

Name    Lucy
Age        4
Type     Cat
Name: B, dtype: object

### Apply Concepts to a Data Set

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
data = iris.data
column_names = iris.feature_names

In [ ]:
#columns
column_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
#rows
len(data)

150

### Slicing Arrays, Lists, and Tuples

Slicing index always starts at 0, which mean the 1st element is [0] and 2nd element is [1].

In [ ]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [ ]:
data[2:5]

array([[4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
data[0:10:2] #intervals

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.4, 2.9, 1.4, 0.2]])

In [ ]:
#Convert an array to a Pandas DataFrame
df = pd.DataFrame(data, columns = column_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
'''saving to google colab
'''
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials


In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
gdrive = GoogleDrive(gauth)


In [ ]:
# note must have df first

from google.colab import drive
drive.mount('/content/drive')

with open('/content/drive/My Drive/WWCode/data/iris.csv', 'w+') as f:
  f.write(df.to_csv())


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [ ]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [ ]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         150.000000        150.000000         150.000000        150.000000
mean            5.843333          3.057333           3.758000          1.199333
std             0.828066          0.435866           1.765298          0.762238
min             4.300000          2.000000           1.000000          0.100000
25%             5.100000          2.800000           1.600000          0.300000
50%             5.800000          3.000000           4.350000          1.300000
75%             6.400000          3.300000           5.100000          1.800000
max             7.900000          4.400000           6.900000          2.500000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
sepal length (cm)    150 non-null float64
sepal width (cm)     150 non-null float64
petal length (cm)    150 non-null float64
petal width (cm)     150 non-null float64
dtypes: float64(4)
memory usage: 4.8 KB


In [ ]:
df.loc[140:]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [ ]:
df.mode()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.0               3.0                1.4               0.2
1                NaN               NaN                1.5               NaN

In [ ]:
df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [ ]:
df['sepal length (cm)'].mean()

5.843333333333335

### Your turn!

Find the mean petal width

In [ ]:
df.groupby(['sepal width (cm)']).mean()

sepal length (cm)  petal length (cm)  petal width (cm)
sepal width (cm)                                                        
2.0                        5.000000           3.500000          1.000000
2.2                        6.066667           4.500000          1.333333
2.3                        5.325000           3.250000          0.975000
2.4                        5.300000           3.600000          1.033333
2.5                        5.762500           4.512500          1.550000
2.6                        6.160000           4.880000          1.420000
2.7                        5.855556           4.622222          1.555556
2.8                        6.335714           5.042857          1.707143
2.9                        6.060000           4.350000          1.320000
3.0                        6.015385           4.234615          1.403846
3.1                        6.036364           3.790909          1.245455
3.2                        5.884615           3.753846          1.261538
3.3                        6.016667           4.200000          1.566667
3.4                        5.316667           2.466667          0.716667
3.5                        5.150000           1.416667          0.300000
3.6                        5.425000           2.475000          0.750000
3.7                        5.266667           1.500000          0.266667
3.8                        6.100000           3.300000          0.900000
3.9                        5.400000           1.500000          0.400000
4.0                        5.800000           1.200000          0.200000
4.1                        5.200000           1.500000          0.100000
4.2                        5.500000           1.400000          0.200000
4.4                        5.700000           1.500000          0.400000

### Your Turn! 

In [ ]:
from sklearn.datasets import load_boston
boston = load_boston()
data = boston.data
column_names = boston.feature_names

In [ ]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
df = pd.DataFrame(data, columns = column_names)
df

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]